# Site settings
title: S. Ahmad Rahiq's Blog
description: "সাব্বির আহমদ রাহিক প্রকাশিত ব্লগসমূহের বিভিন্ন খুঁটিনাটি বিষয়ক আলোচনা, ঘোষণা ও প্রতিক্রিয়া প্রকাশের মাধ্যম"
url: "https://airyrahiq.github.io"
author:
  name: "Sabber Ahmad Rahiq"
  email: "rahiq@airypassion.com"
  url: "https://airyrahiq.github.io"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 7
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins:
- jekyll-seo-tag

# Plugins
gems:
  - jekyll-paginate
gems:
  - jekyll-sitemap

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
